- name: Install and Configure Nginx
  hosts: localhost

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Configure Nginx
      copy:
        dest: /etc/nginx/sites-available/django
        content: |
          server {
            listen 80;
            server_name myapp.test.com;

            location / {
              proxy_pass http://127.0.0.1:8000;
            }
          }

    - name: Remove Default Nginx Site and Restart
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Restart Nginx

    - name: Start & Enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
